services:
  lodgeman-s:
    container_name: lodgeman-s
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "4082:4082"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
