name: Sync Code & Release To Gitee
on:
  push:
    branches: [ main, dev ]
  release:
    types: [published, edited, deleted]
  workflow_dispatch:

jobs:
  mirror_code:
    runs-on: ubuntu-latest
    steps:
      - uses: Yikun/hub-mirror-action@v1.5
        with:
          src: github/${{ secrets.GH_USERNAME }}
          dst: gitee/${{ secrets.GITEE_USERNAME }}
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "${{ github.event.repository.name }}"
          clone_style: https
          force_update: true

  sync_release:
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    needs: mirror_code
    runs-on: ubuntu-latest
    steps:
      - uses: trustedinster/sync-release-gitee@v1.3
        with:
          gitee_owner: ${{ secrets.GITEE_USERNAME }}
          gitee_repo: ${{ github.event.repository.name }}
          gitee_token: ${{ secrets.GITEE_TOKEN }}
          github_owner: ${{ secrets.GH_USERNAME }}
          github_repo: ${{ github.event.repository.name }}
